spring:
  application:
    name: book-service

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  cache:
    type: redis

server:
  port: 8082

jwt:
  secret: mySecretKeymySecretKeymySecretKeymySecretKey