spring:
  application:
    name: user-service

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  cache:
    type: redis

server:
  port: 8081

jwt:
  secret: mySecretKeymySecretKeymySecretKeymySecretKey
  access-token-expiration: 15 #minutes
  refresh-token-expiration: 24 #hours