spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: postgres
    password: password
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: validate
  cache:
    type: redis
  data:
    redis:
      port: 6379
      host: localhost
server:
  port: 8081
